#!/usr/bin/perl

open(AB, $ARGV[0]);
while ($line =<AB>) {
  $line =~ s/^\d+:\s//g;
  $line =~ s/“/"/g;   # <---( be careful here weird chars don't show! )---
  $line =~ s/”/"/g;   # <---( be careful here weird chars don't show! )---
  $line =~ s/‘/'/g;   # <---( be careful here weird chars don't show! )---
  $line =~ s/’/'/g;   # <---( be careful here weird chars don't show! )---
  print $line;
}
close(AB);
